% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Financial Econometrics - Group Assignment},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Financial Econometrics - Group Assignment}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\hypertarget{varianza-italiana}{%
\section{Varianza Italiana}\label{varianza-italiana}}

Group members:

\begin{itemize}
\tightlist
\item
  Baldoni Chiara
\item
  Pinna Paola
\item
  Torella Marta
\end{itemize}

\hypertarget{eda}{%
\subsection{EDA}\label{eda}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"FIN 36182{-}Industry\_Portfolios.CSV"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Date Cnsmr Manuf HiTec  Hlth Other
## 1 192607  5.43  2.73  1.83  1.77  2.13
## 2 192608  2.76  2.33  2.41  4.25  4.35
## 3 192609  2.16 -0.44  1.06  0.69  0.29
## 4 192610 -3.90 -2.42 -2.26 -0.57 -2.84
## 5 192611  3.70  2.50  3.07  5.42  2.11
## 6 192612  3.62  2.76  1.03  0.11  3.47
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anyDuplicated}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[, }\DecValTok{2}\SpecialCharTok{:}\DecValTok{6}\NormalTok{] }\OtherTok{\textless{}{-}}\NormalTok{ data[, }\DecValTok{2}\SpecialCharTok{:}\DecValTok{6}\NormalTok{] }\SpecialCharTok{/} \DecValTok{100} \DocumentationTok{\#\# Convert returns to decimal form as asked}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Date   Cnsmr   Manuf   HiTec    Hlth   Other
## 1 192607  0.0543  0.0273  0.0183  0.0177  0.0213
## 2 192608  0.0276  0.0233  0.0241  0.0425  0.0435
## 3 192609  0.0216 -0.0044  0.0106  0.0069  0.0029
## 4 192610 -0.0390 -0.0242 -0.0226 -0.0057 -0.0284
## 5 192611  0.0370  0.0250  0.0307  0.0542  0.0211
## 6 192612  0.0362  0.0276  0.0103  0.0011  0.0347
\end{verbatim}

\hypertarget{task-1}{%
\subsection{Task 1}\label{task-1}}

\hypertarget{report-the-arithmetic-mean-of-the-returns-for-each-of-the-five-industries-over-the-entire-sample}{%
\subsubsection{1. Report the arithmetic mean of the returns for each of
the five industries over the entire
sample}\label{report-the-arithmetic-mean-of-the-returns-for-each-of-the-five-industries-over-the-entire-sample}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{monthly\_means }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(data[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{, }\StringTok{"Other"}\NormalTok{)]) }
\NormalTok{annualized\_means }\OtherTok{\textless{}{-}}\NormalTok{ monthly\_means }\SpecialCharTok{*} \DecValTok{12}
\NormalTok{annualized\_means }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(annualized\_means, }\DecValTok{4}\NormalTok{)}
\NormalTok{annualized\_means}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Cnsmr  Manuf  HiTec   Hlth  Other 
## 0.1215 0.1152 0.1203 0.1288 0.1104
\end{verbatim}

\hypertarget{report-the-standard-deviation-of-the-returns-for-each-of-the-five-industries-over-the-entire-sample}{%
\subsubsection{2. Report the standard deviation of the returns for each
of the five industries over the entire
sample}\label{report-the-standard-deviation-of-the-returns-for-each-of-the-five-industries-over-the-entire-sample}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{monthly\_std }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(data[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{, }\StringTok{"Other"}\NormalTok{)], }\DecValTok{2}\NormalTok{, sd)}
\NormalTok{annualized\_std }\OtherTok{\textless{}{-}}\NormalTok{ monthly\_std }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{12}\NormalTok{)}
\NormalTok{annualized\_std }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(annualized\_std, }\DecValTok{4}\NormalTok{)}
\NormalTok{annualized\_std}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Cnsmr  Manuf  HiTec   Hlth  Other 
## 0.1828 0.1905 0.1935 0.1910 0.2211
\end{verbatim}

\hypertarget{report-the-sharpe-ratio-of-each-industry}{%
\subsubsection{3. Report the Sharpe ratio of each
industry}\label{report-the-sharpe-ratio-of-each-industry}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sharpe\_ratios }\OtherTok{\textless{}{-}}\NormalTok{ annualized\_means }\SpecialCharTok{/}\NormalTok{ annualized\_std}
\NormalTok{sharpe\_ratios }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(sharpe\_ratios, }\DecValTok{4}\NormalTok{)}
\NormalTok{sharpe\_ratios}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Cnsmr  Manuf  HiTec   Hlth  Other 
## 0.6647 0.6047 0.6217 0.6743 0.4993
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{results\_table1 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Mean\_Returns =}\NormalTok{ annualized\_means,}
  \AttributeTok{Std\_Returns =}\NormalTok{ annualized\_std,}
  \AttributeTok{Sharpe\_Ratio =}\NormalTok{ sharpe\_ratios}
\NormalTok{ )}
\NormalTok{results\_table1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Mean_Returns Std_Returns Sharpe_Ratio
## Cnsmr       0.1215      0.1828       0.6647
## Manuf       0.1152      0.1905       0.6047
## HiTec       0.1203      0.1935       0.6217
## Hlth        0.1288      0.1910       0.6743
## Other       0.1104      0.2211       0.4993
\end{verbatim}

\hypertarget{is-there-evidence-that-technology-stocks-have-better-risk-adjusted-returns}{%
\subsubsection{4. Is there evidence that technology stocks have better
risk-adjusted
returns?}\label{is-there-evidence-that-technology-stocks-have-better-risk-adjusted-returns}}

Based on the results, technology stocks (HiTec) have a Sharpe ratio of
0.6216, indicating better risk-adjusted returns compared to the
manufacturing (0.6045) and other sectors (0.4994). However, they do not
outperform the consumer (0.6646) and health industries (0.6746), which
exhibit higher Sharpe ratios. Therefore, while technology stocks offer
relatively good risk-adjusted returns, they are not the best performers
overall, as both the consumer and health sectors deliver better
risk-adjusted outcomes.

\hypertarget{provide-a-table-55-with-the-sample-correlation-between-the-returns-of-the-five-industries.-comment-briefly.}{%
\subsubsection{5. Provide a table (5×5) with the sample correlation
between the returns of the five industries. Comment
briefly.}\label{provide-a-table-55-with-the-sample-correlation-between-the-returns-of-the-five-industries.-comment-briefly.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{correlation\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{, }\StringTok{"Other"}\NormalTok{)])}
\NormalTok{correlation\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(correlation\_matrix, }\DecValTok{4}\NormalTok{)}
\NormalTok{correlation\_matrix}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Cnsmr  Manuf  HiTec   Hlth  Other
## Cnsmr 1.0000 0.8670 0.8164 0.7739 0.8716
## Manuf 0.8670 1.0000 0.7996 0.7427 0.8924
## HiTec 0.8164 0.7996 1.0000 0.7072 0.7932
## Hlth  0.7739 0.7427 0.7072 1.0000 0.7371
## Other 0.8716 0.8924 0.7932 0.7371 1.0000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{kable}\NormalTok{(correlation\_matrix, }\AttributeTok{caption =} \StringTok{"Correlation Matrix of Industry Returns"}\NormalTok{, }\AttributeTok{format =} \StringTok{"html"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Correlation Matrix of Industry Returns

Cnsmr

Manuf

HiTec

Hlth

Other

Cnsmr

1.0000

0.8670

0.8164

0.7739

0.8716

Manuf

0.8670

1.0000

0.7996

0.7427

0.8924

HiTec

0.8164

0.7996

1.0000

0.7072

0.7932

Hlth

0.7739

0.7427

0.7072

1.0000

0.7371

Other

0.8716

0.8924

0.7932

0.7371

1.0000

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(corrplot)}
\FunctionTok{corrplot}\NormalTok{(correlation\_matrix, }\AttributeTok{method =} \StringTok{"color"}\NormalTok{, }\AttributeTok{type =} \StringTok{"upper"}\NormalTok{, }
         \AttributeTok{tl.col =} \StringTok{"black"}\NormalTok{, }\AttributeTok{tl.srt =} \DecValTok{45}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{financial_econometrics_files/figure-latex/unnamed-chunk-7-1.pdf}
The correlation matrix indicates that all five industries have positive
correlations with each other, suggesting that their returns tend to move
in the same direction. The strongest correlations are between
Manufacturing and Other (0.8924) and between Manufacturing and Consumer
(0.8670), indicating that these industries have highly synchronized
return movements. On the other hand, the weakest correlations are
between Technology and Health (0.7072), and between these two industries
and the others, implying that Technology and Health exhibit slightly
more independent return patterns. While the positive correlations across
all industries suggest some degree of co-movement, the relatively lower
correlations for Technology and Health indicate potential
diversification benefits, though the absence of negative correlations
limits the extent of diversification.

\hypertarget{construct-a-time-series-of-the-simple-non-cumulative-returns-of-a-portfolio-where-capital-is-allocated-equally-across-the-first-four-industries-excluding-other.-report-the-arithmetic-mean-standard-deviation-and-sharpe.-comment-briefly-on-the-gains-achieved-by-this-diversified-portfolio.}{%
\subsubsection{6. Construct a time series of the simple, non-cumulative
returns of a portfolio where capital is allocated equally across the
first four industries (excluding Other). Report the arithmetic mean,
standard deviation and Sharpe. Comment briefly on the gains achieved by
this diversified
portfolio.}\label{construct-a-time-series-of-the-simple-non-cumulative-returns-of-a-portfolio-where-capital-is-allocated-equally-across-the-first-four-industries-excluding-other.-report-the-arithmetic-mean-standard-deviation-and-sharpe.-comment-briefly-on-the-gains-achieved-by-this-diversified-portfolio.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{portfolio\_returns }\OtherTok{\textless{}{-}} \FunctionTok{rowMeans}\NormalTok{(data[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{)]) }
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns }\OtherTok{\textless{}{-}}\NormalTok{ portfolio\_returns}
\NormalTok{mean\_portfolio }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(portfolio\_returns)}
\NormalTok{sd\_portfolio }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(portfolio\_returns)}

\NormalTok{annualized\_mean\_portfolio }\OtherTok{\textless{}{-}}\NormalTok{ mean\_portfolio }\SpecialCharTok{*} \DecValTok{12}
\NormalTok{annualized\_sd\_portfolio }\OtherTok{\textless{}{-}}\NormalTok{ sd\_portfolio }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{12}\NormalTok{)}
\NormalTok{sharpe\_ratio\_portfolio }\OtherTok{\textless{}{-}}\NormalTok{ annualized\_mean\_portfolio }\SpecialCharTok{/}\NormalTok{ annualized\_sd\_portfolio}

\NormalTok{portfolio\_results }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"Annualized Mean Return"}\NormalTok{, }\StringTok{"Annualized Standard Deviation"}\NormalTok{, }\StringTok{"Sharpe Ratio"}\NormalTok{),}
  \AttributeTok{Value =} \FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(annualized\_mean\_portfolio, annualized\_sd\_portfolio, sharpe\_ratio\_portfolio), }\DecValTok{4}\NormalTok{)}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(portfolio\_results)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                          Metric  Value
## 1        Annualized Mean Return 0.1214
## 2 Annualized Standard Deviation 0.1734
## 3                  Sharpe Ratio 0.7004
\end{verbatim}

The diversified portfolio, which allocates capital equally across the
first four industries, achieves an annualized mean return of 12.14\% and
an annualized standard deviation of 17.34\%, resulting in a Sharpe ratio
of 0.7004. This Sharpe ratio indicates that the portfolio offers better
risk-adjusted returns than some individual industries, such as
Manufacturing (0.6045) and Other (0.4994). It also slightly outperforms
Technology (0.6216), suggesting that diversification has improved the
portfolio's performance relative to risk. However, the gains from
diversification are not substantial, as the portfolio's Sharpe ratio is
only marginally higher than that of Health (0.6746) and Consumer
(0.6646). Overall, diversification provides some benefit, but the
improvement in risk-adjusted returns is moderate.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Date }\OtherTok{\textless{}{-}} \FunctionTok{as.character}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Date)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Date }\OtherTok{\textless{}{-}} \FunctionTok{paste0}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Date, }\StringTok{"01"}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Date }\OtherTok{\textless{}{-}} \FunctionTok{as.Date}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Date, }\AttributeTok{format =} \StringTok{"\%Y\%m\%d"}\NormalTok{)}

\NormalTok{plot\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Date =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Date, }\AttributeTok{Portfolio\_Returns =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns)}
\FunctionTok{ggplot}\NormalTok{(plot\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date, }\AttributeTok{y =}\NormalTok{ Portfolio\_Returns)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Portfolio Returns Over Time"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Portfolio Returns"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{financial_econometrics_files/figure-latex/unnamed-chunk-9-1.pdf}

The portfolio returns exhibit significant volatility, especially in the
earlier periods before the 1950s, with large spikes in both positive and
negative directions. This high volatility is particularly evident around
historical market crashes, such as the Great Depression in the 1930s and
the 2008 financial crisis. After World War II, the portfolio returns
become more stable, with fewer extreme fluctuations, though volatility
remains, particularly during financial crises. In the last two decades,
there has been a noticeable increase in volatility, likely reflecting
events like the dot-com bubble, the 2008 crisis, and the COVID-19 market
disruptions. Overall, while the portfolio appears more stable post-1950,
significant market events continue to cause sharp fluctuations.

\hypertarget{task-2}{%
\subsection{Task 2}\label{task-2}}

In this task you will treat the portfolio you computed in Task 1, point
(6), as the market portfolio, denote its returns as Rm, and will
estimate and interpret beta and alpha coefficients in the context of the
CAPM.

\hypertarget{compute-the-kurtosis-and-skeweness-of-rm}{%
\subsubsection{1. Compute the kurtosis and skeweness of
Rm}\label{compute-the-kurtosis-and-skeweness-of-rm}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(portfolio\_returns)}

\NormalTok{skewness\_value }\OtherTok{\textless{}{-}}\NormalTok{ (n }\SpecialCharTok{/}\NormalTok{ ((n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{))) }\SpecialCharTok{*} \FunctionTok{sum}\NormalTok{(((portfolio\_returns }\SpecialCharTok{{-}}\NormalTok{ mean\_portfolio) }\SpecialCharTok{/}\NormalTok{ sd\_portfolio)}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{kurtosis\_value }\OtherTok{\textless{}{-}}\NormalTok{ (n }\SpecialCharTok{*}\NormalTok{ (n }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ ((n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{3}\NormalTok{))) }\SpecialCharTok{*} 
                  \FunctionTok{sum}\NormalTok{(((portfolio\_returns }\SpecialCharTok{{-}}\NormalTok{ mean\_portfolio) }\SpecialCharTok{/}\NormalTok{ sd\_portfolio)}\SpecialCharTok{\^{}}\DecValTok{4}\NormalTok{) }\SpecialCharTok{{-}} 
\NormalTok{                  (}\DecValTok{3} \SpecialCharTok{*}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ ((n }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{3}\NormalTok{)))}
\NormalTok{kurtosis\_value }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(kurtosis\_value, }\DecValTok{4}\NormalTok{)}
\NormalTok{skewness\_value }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(skewness\_value, }\DecValTok{4}\NormalTok{)}

\NormalTok{portfolio\_results2 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"Kurtosis"}\NormalTok{, }\StringTok{"Skewness"}\NormalTok{),}
  \AttributeTok{Value =} \FunctionTok{c}\NormalTok{(kurtosis\_value, skewness\_value)}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(portfolio\_results2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Metric  Value
## 1 Kurtosis 7.3218
## 2 Skewness 0.0237
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{returns =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ returns)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(portfolio\_returns, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
                            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(portfolio\_returns, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),}
                \AttributeTok{color =} \StringTok{"green"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Distribution of Portfolio Returns with Normal Distribution Overlay"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Portfolio Returns"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{financial_econometrics_files/figure-latex/unnamed-chunk-11-1.pdf}

\hypertarget{how-do-the-values-in-1-compare-with-the-normal-distribution}{%
\subsubsection{2. How do the values in (1) compare with the normal
distribution?}\label{how-do-the-values-in-1-compare-with-the-normal-distribution}}

The portfolio returns exhibit a kurtosis of 7.3218, which is
significantly higher than the normal distribution's kurtosis of 3,
indicating the presence of fat tails. This suggests that the portfolio
is more likely to experience extreme returns, both positive and
negative, compared to a normal distribution. In contrast, the skewness
of 0.0237 is very close to zero, implying that the distribution of
returns is symmetric, with no significant bias toward either side.
Overall, while the portfolio returns are prone to extreme fluctuations,
these events are equally likely to be positive or negative, reflecting a
balance in the distribution's shape.

Moreover, the above plot shows the distribution of portfolio returns
(blue histogram with red density curve) overlaid with a normal
distribution (green dashed line). The portfolio returns exhibit fatter
tails compared to the normal distribution, particularly on the left
side, which is consistent with the high kurtosis observed earlier,
indicating a higher probability of extreme returns. The distribution is
also roughly symmetric, aligning with the nearly zero skewness, showing
no significant bias toward either positive or negative returns.
Additionally, the portfolio's return distribution has a slightly higher
peak than the normal curve, suggesting a greater concentration of
returns near the mean. Overall, the portfolio returns deviate from the
normal distribution, with a greater chance of extreme events and a
higher central concentration of values.

\hypertarget{repeat-point-1-but-eliminating-the-first-70-years-of-data-i.e.-from-199706.}{%
\subsubsection{3. Repeat point (1), but eliminating the first 70 years
of data (i.e.~from
199706).}\label{repeat-point-1-but-eliminating-the-first-70-years-of-data-i.e.-from-199706.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_filtered }\OtherTok{\textless{}{-}}\NormalTok{ data[data}\SpecialCharTok{$}\NormalTok{Date }\SpecialCharTok{\textgreater{}=} \FunctionTok{as.Date}\NormalTok{(}\StringTok{"1997{-}06{-}01"}\NormalTok{), ]}
\NormalTok{portfolio\_returns\_filtered }\OtherTok{\textless{}{-}}\NormalTok{ data\_filtered}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns}

\NormalTok{n\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(portfolio\_returns\_filtered)}
\NormalTok{mean\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(portfolio\_returns\_filtered)}
\NormalTok{sd\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(portfolio\_returns\_filtered)}

\NormalTok{skewness\_filtered }\OtherTok{\textless{}{-}}\NormalTok{ (n\_filtered }\SpecialCharTok{/}\NormalTok{ ((n\_filtered }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n\_filtered }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{))) }\SpecialCharTok{*} 
                      \FunctionTok{sum}\NormalTok{(((portfolio\_returns\_filtered }\SpecialCharTok{{-}}\NormalTok{ mean\_filtered) }\SpecialCharTok{/}\NormalTok{ sd\_filtered)}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{)}
\NormalTok{kurtosis\_filtered }\OtherTok{\textless{}{-}}\NormalTok{ (n\_filtered }\SpecialCharTok{*}\NormalTok{ (n\_filtered }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ ((n\_filtered }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n\_filtered }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n\_filtered }\SpecialCharTok{{-}} \DecValTok{3}\NormalTok{))) }\SpecialCharTok{*} 
                      \FunctionTok{sum}\NormalTok{(((portfolio\_returns\_filtered }\SpecialCharTok{{-}}\NormalTok{ mean\_filtered) }\SpecialCharTok{/}\NormalTok{ sd\_filtered)}\SpecialCharTok{\^{}}\DecValTok{4}\NormalTok{) }\SpecialCharTok{{-}} 
\NormalTok{                      (}\DecValTok{3} \SpecialCharTok{*}\NormalTok{ (n\_filtered }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ ((n\_filtered }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (n\_filtered }\SpecialCharTok{{-}} \DecValTok{3}\NormalTok{)))}

\NormalTok{skewness\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(skewness\_filtered, }\DecValTok{4}\NormalTok{)}
\NormalTok{kurtosis\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(kurtosis\_filtered, }\DecValTok{4}\NormalTok{)}

\NormalTok{portfolio\_results3 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"Kurtosis"}\NormalTok{, }\StringTok{"Skewness"}\NormalTok{),}
  \AttributeTok{Value =} \FunctionTok{c}\NormalTok{(kurtosis\_filtered, skewness\_filtered)}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(portfolio\_results3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Metric   Value
## 1 Kurtosis  0.7682
## 2 Skewness -0.5147
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{returns =}\NormalTok{ portfolio\_returns\_filtered), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ returns)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)), }\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(portfolio\_returns\_filtered, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
                            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(portfolio\_returns\_filtered, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),}
                \AttributeTok{color =} \StringTok{"green"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Distribution of Filtered Portfolio Returns with Normal Distribution Overlay"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Portfolio Returns"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{financial_econometrics_files/figure-latex/unnamed-chunk-13-1.pdf}

\hypertarget{compute-and-report-the-covariance-of-the-first-four-industries-with-rm}{%
\subsubsection{4. Compute and report the covariance of the first four
industries with
Rm}\label{compute-and-report-the-covariance-of-the-first-four-industries-with-rm}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cov\_Cnsmr\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Cnsmr, data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{cov\_Manuf\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Manuf, data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{cov\_HiTec\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{HiTec, data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{cov\_Hlth\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Hlth, data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}

\NormalTok{cov\_Cnsmr\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(cov\_Cnsmr\_Rm, }\DecValTok{4}\NormalTok{)}
\NormalTok{cov\_Manuf\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(cov\_Manuf\_Rm, }\DecValTok{4}\NormalTok{)}
\NormalTok{cov\_HiTec\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(cov\_HiTec\_Rm, }\DecValTok{4}\NormalTok{)}
\NormalTok{cov\_Hlth\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(cov\_Hlth\_Rm, }\DecValTok{4}\NormalTok{)}

\NormalTok{covariances }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Industry =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{),}
  \AttributeTok{Covariance\_with\_Rm =} \FunctionTok{c}\NormalTok{(cov\_Cnsmr\_Rm, cov\_Manuf\_Rm, cov\_HiTec\_Rm, cov\_Hlth\_Rm)}
\NormalTok{)}

\FunctionTok{print}\NormalTok{(covariances)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Industry Covariance_with_Rm
## 1    Cnsmr             0.0025
## 2    Manuf             0.0026
## 3    HiTec             0.0025
## 4     Hlth             0.0024
\end{verbatim}

\hypertarget{use-the-results-obtained-so-far-to-compute-the-beta-values-for-the-first-four-industries-for-the-full-sample}{%
\subsubsection{5. Use the results obtained so far to compute the beta
values for the first four industries for the full
sample}\label{use-the-results-obtained-so-far-to-compute-the-beta-values-for-the-first-four-industries-for-the-full-sample}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# calculate the variance of the portfolio returns (Rm)}
\NormalTok{var\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{var\_Rm }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(var\_Rm, }\DecValTok{4}\NormalTok{)}

\CommentTok{\# calculate the beta values for each industry}
\NormalTok{beta\_Cnsmr }\OtherTok{\textless{}{-}}\NormalTok{ cov\_Cnsmr\_Rm }\SpecialCharTok{/}\NormalTok{ var\_Rm}
\NormalTok{beta\_Manuf }\OtherTok{\textless{}{-}}\NormalTok{ cov\_Manuf\_Rm }\SpecialCharTok{/}\NormalTok{ var\_Rm}
\NormalTok{beta\_HiTec }\OtherTok{\textless{}{-}}\NormalTok{ cov\_HiTec\_Rm }\SpecialCharTok{/}\NormalTok{ var\_Rm}
\NormalTok{beta\_Hlth }\OtherTok{\textless{}{-}}\NormalTok{ cov\_Hlth\_Rm }\SpecialCharTok{/}\NormalTok{ var\_Rm}

\NormalTok{beta\_Cnsmr }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_Cnsmr, }\DecValTok{4}\NormalTok{)}
\NormalTok{beta\_Manuf }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_Manuf, }\DecValTok{4}\NormalTok{)}
\NormalTok{beta\_HiTec }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_HiTec, }\DecValTok{4}\NormalTok{)}
\NormalTok{beta\_Hlth }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_Hlth, }\DecValTok{4}\NormalTok{)}

\NormalTok{beta\_values }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Industry =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{),}
  \AttributeTok{Beta =} \FunctionTok{c}\NormalTok{(beta\_Cnsmr, beta\_Manuf, beta\_HiTec, beta\_Hlth)}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(beta\_values)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Industry Beta
## 1    Cnsmr 1.00
## 2    Manuf 1.04
## 3    HiTec 1.00
## 4     Hlth 0.96
\end{verbatim}

\hypertarget{compute-the-beta-values-for-the-first-four-industries-for-the-sample-starting-from-199706.-briefly-comment-on-how-results-compare-with-those-in-point-5}{%
\subsubsection{6. Compute the beta values for the first four industries
for the sample starting from 199706. Briefly comment on how results
compare with those in point
(5)}\label{compute-the-beta-values-for-the-first-four-industries-for-the-sample-starting-from-199706.-briefly-comment-on-how-results-compare-with-those-in-point-5}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{var\_Rm\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(portfolio\_returns\_filtered, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}

\NormalTok{beta\_Cnsmr\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data\_filtered}\SpecialCharTok{$}\NormalTok{Cnsmr, data\_filtered}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ var\_Rm\_filtered}
\NormalTok{beta\_Manuf\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data\_filtered}\SpecialCharTok{$}\NormalTok{Manuf, data\_filtered}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ var\_Rm\_filtered}
\NormalTok{beta\_HiTec\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data\_filtered}\SpecialCharTok{$}\NormalTok{HiTec, data\_filtered}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ var\_Rm\_filtered}
\NormalTok{beta\_Hlth\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(data\_filtered}\SpecialCharTok{$}\NormalTok{Hlth, data\_filtered}\SpecialCharTok{$}\NormalTok{Portfolio\_Returns, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ var\_Rm\_filtered}

\NormalTok{beta\_Cnsmr\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_Cnsmr\_filtered, }\DecValTok{4}\NormalTok{)}
\NormalTok{beta\_Manuf\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_Manuf\_filtered, }\DecValTok{4}\NormalTok{)}
\NormalTok{beta\_HiTec\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_HiTec\_filtered, }\DecValTok{4}\NormalTok{)}
\NormalTok{beta\_Hlth\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(beta\_Hlth\_filtered, }\DecValTok{4}\NormalTok{)}

\NormalTok{beta\_values\_filtered }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Industry =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{),}
  \AttributeTok{Beta\_Filtered =} \FunctionTok{c}\NormalTok{(beta\_Cnsmr\_filtered, beta\_Manuf\_filtered, beta\_HiTec\_filtered, beta\_Hlth\_filtered)}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(beta\_values\_filtered)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Industry Beta_Filtered
## 1    Cnsmr        0.9236
## 2    Manuf        0.9533
## 3    HiTec        1.3305
## 4     Hlth        0.7926
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{comparison }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Industry =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{),}
  \AttributeTok{Beta\_Full\_Sample =} \FunctionTok{c}\NormalTok{(beta\_Cnsmr, beta\_Manuf, beta\_HiTec, beta\_Hlth),  }\CommentTok{\# point 5}
  \AttributeTok{Beta\_Filtered =} \FunctionTok{c}\NormalTok{(beta\_Cnsmr\_filtered, beta\_Manuf\_filtered, beta\_HiTec\_filtered, beta\_Hlth\_filtered)  }\CommentTok{\# point 6}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(comparison)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Industry Beta_Full_Sample Beta_Filtered
## 1    Cnsmr             1.00        0.9236
## 2    Manuf             1.04        0.9533
## 3    HiTec             1.00        1.3305
## 4     Hlth             0.96        0.7926
\end{verbatim}

The comparison of beta values between the full sample and the post-June
1997 period shows some notable changes. For Consumer stocks, the beta
decreases from 1.00 in the full sample to 0.9236 in the filtered period,
indicating slightly less sensitivity to the market. Similarly,
Manufacturing shows a reduction in beta from 1.04 to 0.9533, suggesting
that its returns are less volatile relative to the market in the more
recent period. In contrast, Technology stocks see a significant increase
in beta from 1.00 to 1.3305, implying a stronger reaction to market
movements in the post-1997 period. Lastly, Health stocks exhibit a lower
beta, decreasing from 0.96 to 0.7926, indicating that they have become
less sensitive to market fluctuations. Overall, the results suggest that
Technology has become more volatile relative to the market, while the
other industries show reduced sensitivity in the more recent period.

\hypertarget{assuming-a-risk-free-rate-of-5-compute-jensens-alpha-for-each-of-the-first-four-industries-on-the-full-sample.-report-the-alpha-in-percentage-terms.-briefly-discuss-your-results}{%
\subsubsection{7. Assuming a risk-free rate of 5\%, compute Jensen's
alpha for each of the first four industries (on the full sample). Report
the alpha in percentage terms. Briefly discuss your
results}\label{assuming-a-risk-free-rate-of-5-compute-jensens-alpha-for-each-of-the-first-four-industries-on-the-full-sample.-report-the-alpha-in-percentage-terms.-briefly-discuss-your-results}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{annualized\_returns\_industries }\OtherTok{\textless{}{-}}\NormalTok{ annualized\_means}
\NormalTok{risk\_free\_rate }\OtherTok{\textless{}{-}} \FloatTok{0.05}

\NormalTok{alpha\_Cnsmr }\OtherTok{\textless{}{-}}\NormalTok{ (annualized\_returns\_industries[}\StringTok{"Cnsmr"}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ (risk\_free\_rate }\SpecialCharTok{+}\NormalTok{ beta\_Cnsmr }\SpecialCharTok{*}\NormalTok{ (annualized\_mean\_portfolio }\SpecialCharTok{{-}}\NormalTok{ risk\_free\_rate))) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{alpha\_Manuf }\OtherTok{\textless{}{-}}\NormalTok{ (annualized\_returns\_industries[}\StringTok{"Manuf"}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ (risk\_free\_rate }\SpecialCharTok{+}\NormalTok{ beta\_Manuf }\SpecialCharTok{*}\NormalTok{ (annualized\_mean\_portfolio }\SpecialCharTok{{-}}\NormalTok{ risk\_free\_rate))) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{alpha\_HiTec }\OtherTok{\textless{}{-}}\NormalTok{ (annualized\_returns\_industries[}\StringTok{"HiTec"}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ (risk\_free\_rate }\SpecialCharTok{+}\NormalTok{ beta\_HiTec }\SpecialCharTok{*}\NormalTok{ (annualized\_mean\_portfolio }\SpecialCharTok{{-}}\NormalTok{ risk\_free\_rate))) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{alpha\_Hlth }\OtherTok{\textless{}{-}}\NormalTok{ (annualized\_returns\_industries[}\StringTok{"Hlth"}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ (risk\_free\_rate }\SpecialCharTok{+}\NormalTok{ beta\_Hlth }\SpecialCharTok{*}\NormalTok{ (annualized\_mean\_portfolio }\SpecialCharTok{{-}}\NormalTok{ risk\_free\_rate))) }\SpecialCharTok{*} \DecValTok{100}

\NormalTok{jensens\_alpha }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Industry =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cnsmr"}\NormalTok{, }\StringTok{"Manuf"}\NormalTok{, }\StringTok{"HiTec"}\NormalTok{, }\StringTok{"Hlth"}\NormalTok{),}
  \AttributeTok{Alpha =} \FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(alpha\_Cnsmr, alpha\_Manuf, alpha\_HiTec, alpha\_Hlth), }\DecValTok{4}\NormalTok{)}
\NormalTok{)}
\FunctionTok{print}\NormalTok{(jensens\_alpha)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Industry   Alpha
## Cnsmr    Cnsmr  0.0051
## Manuf    Manuf -0.9107
## HiTec    HiTec -0.1149
## Hlth      Hlth  1.0209
\end{verbatim}

The Jensen's alpha results, reported in percentage terms, show varying
performance across the four industries. Consumer stocks have an alpha of
0.0051\%, indicating performance roughly in line with expectations under
the CAPM model. Manufacturing stocks, on the other hand, have a negative
alpha of -0.9107\%, meaning they significantly underperformed relative
to what the CAPM would predict. Similarly, Technology stocks exhibit a
negative alpha of -0.1149\%, suggesting a slight underperformance. In
contrast, Health stocks stand out with a positive alpha of 1.0209\%,
indicating that this sector outperformed its expected return by over
1\%, given its risk and the market conditions. Overall, the Health
sector performed well above expectations, while Manufacturing and
Technology stocks underperformed.

\hypertarget{task-3}{%
\subsection{Task 3}\label{task-3}}

Use the lm( ) function to run a few regressions:

\hypertarget{regress-rmt-on-an-intercept-and-on-rmt1.-report-estimates-and-t-statistics.-briefly-interpret-the-results}{%
\subsubsection{1. Regress Rm(t) on an intercept and on Rm(t−1). Report
estimates and t-statistics. Briefly interpret the
results}\label{regress-rmt-on-an-intercept-and-on-rmt1.-report-estimates-and-t-statistics.-briefly-interpret-the-results}}

\hypertarget{regress-rmt-on-an-intercept-and-on-pmt1pmt131.-report-estimates-and-t-statistics.-briefly-interpret-the-results}{%
\subsubsection{2. Regress Rm(t) on an intercept and on
(Pm(t−1)/Pm(t−13)−1). Report estimates and t-statistics. Briefly
interpret the
results}\label{regress-rmt-on-an-intercept-and-on-pmt1pmt131.-report-estimates-and-t-statistics.-briefly-interpret-the-results}}

\hypertarget{are-the-t-statistics-reported-by-lm-in-2-reliable-explain}{%
\subsubsection{3. Are the t-statistics reported by lm( ) in (2)
reliable?
Explain}\label{are-the-t-statistics-reported-by-lm-in-2-reliable-explain}}

\hypertarget{regress-rmt-on-an-intercept-and-on-absrmt.-report-estimates-and-t-statistics.-briefly-interpret-the-results}{%
\subsubsection{4. Regress Rm(t) on an intercept and on abs(Rm(t)).
Report estimates and t-statistics. Briefly interpret the
results}\label{regress-rmt-on-an-intercept-and-on-absrmt.-report-estimates-and-t-statistics.-briefly-interpret-the-results}}

\hypertarget{repeat-1-on-data-from-199706.-delete-all-data-prior-to-199706-then-compute-lagged-returns.-comment-briefly}{%
\subsubsection{5. Repeat (1) on data from 199706. (Delete all data prior
to 199706, then compute lagged returns). Comment
briefly}\label{repeat-1-on-data-from-199706.-delete-all-data-prior-to-199706-then-compute-lagged-returns.-comment-briefly}}

\hypertarget{repeat-2-on-data-from-199706.-delete-all-data-prior-to-199706-then-compute-lagged-returns.-comment-briefly}{%
\subsubsection{6.Repeat (2) on data from 199706. (Delete all data prior
to 199706, then compute lagged returns). Comment
briefly}\label{repeat-2-on-data-from-199706.-delete-all-data-prior-to-199706-then-compute-lagged-returns.-comment-briefly}}

\hypertarget{repeat-4-on-data-from-199706.-comment-briefly}{%
\subsubsection{7. Repeat (4) on data from 199706. Comment
briefly}\label{repeat-4-on-data-from-199706.-comment-briefly}}

\end{document}
